# Generated by Django 4.1.7 on 2023-03-30 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0004_veiculo_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='Nome',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='modelo',
            field=models.CharField(default='fit', max_length=50),
            preserve_default=False,
        ),
    ]
