# Generated by Django 4.1.7 on 2023-03-30 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0005_remove_veiculo_nome_veiculo_modelo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='veiculo',
            old_name='modelo',
            new_name='Modelo',
        ),
    ]
