# Generated by Django 4.2.1 on 2023-05-15 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0007_alter_cor_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='veiculo',
            old_name='Ano',
            new_name='ano',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='Categoria',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='Cor',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='Marca',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='Modelo',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='Preco',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='acessorios',
            field=models.ManyToManyField(to='garagem.acessorio'),
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='garagem.categoria')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='garagem.marca')),
            ],
        ),
        migrations.AddField(
            model_name='veiculo',
            name='cor',
            field=models.ForeignKey(default=2000, on_delete=django.db.models.deletion.PROTECT, to='garagem.cor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veiculo',
            name='modelo',
            field=models.ForeignKey(default=2000, on_delete=django.db.models.deletion.PROTECT, to='garagem.modelo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veiculo',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
